# MySQL 配置示例（生产环境使用）
# 使用方法：在 application.yml 中设置 spring.profiles.active=mysql

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/doc_studio?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema-mysql.sql
      data-locations: classpath:db/data.sql

